# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180330_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 1, 12, 58, 41, 306654, tzinfo=utc)),
        ),
    ]
